public class PaginationExtension {
    /*
    public ApexPages.StandardSetController setController {get; set;}
    
    public list<Account> displayedAccounts {
        get {
            return setController.getRecord();
        }
        set;
    }
    
    public PaginationExtension(ApexPages.StandardSetController ctrl) {
        // setController = ctrl; can't use this, because it take apex page, not our define page
        setController = new ApexPages.StandardSetController([SELECT Id, Name, BillingStreet, Type FROM Account]);
        setController.setPageSIze(5);
    }
*/
}